### PR TITLE
fix: support multiple assets (findRegularFontFiles)

### PR DESCRIPTION
**Pull request by mochiya98**
make it possible to find all assets.

### CODE REVIEW

**Comment by patrickhulce** [comment]
Would you mind explaining the use case and/or following up with a test so we capture this better and don't break in the future?

**Comment by mochiya98** [comment]
Thanks @patrickhulce
ok. I'll add tests later.  

--------------

I would be happy if you could fix `nukecss` package. (for debugging)  
I couldn't install on latest environment.

https://github.com/patrickhulce/nukecss/blob/master/package.json#L6

```diff
  "bin": {
-    "bin/nukecss.js": "nukecss"
+    "nukecss": "bin/nukecss.js"
  },
```

https://github.com/patrickhulce/nukecss-webpack/blob/master/package.json#L36
https://github.com/patrickhulce/fontmin-webpack/blob/master/package.json#L50

```
fontmin-webpack (devDependencies)
 -> nukecss-webpack
   -> nukecss
```

**Comment by patrickhulce** [comment]
Oh sure, yeah I never documented/officially supported a real CLI sorry about that!

**Comment by mochiya98** [comment]
thank you for you help.  
check out these :)

**Pull request merged**
